server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Indispensable pour React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api/ vers le backend PHP
    location /api/ {
        proxy_pass http://backend:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Username $http_x_username;
        proxy_set_header X-Real-IP $remote_addr;
    }
}