apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bda-backend-hpa
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: bda
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: {{ .Values.hpa.backend.minReplicas }}
  maxReplicas: {{ .Values.hpa.backend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.backend.cpuThreshold }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bda-frontend-hpa
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: bda
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: {{ .Values.hpa.frontend.minReplicas }}
  maxReplicas: {{ .Values.hpa.frontend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.frontend.cpuThreshold }}
