apiVersion: v1
kind: Secret
metadata:
  name: bda-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: bda
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  DB_NAME: dmVyc2VtZW50cw==
  DB_USER: dmVyc2VtZW50X3VzZXI=
  DB_PASS: {{ .Values.database.passwordBase64 }}
  DB_PORT: NTQzMg==
  DB_HOST: cG9zdGdyZXM=
