# ============================================================
# inventory.ini
# On cible localhost car Ansible tourne sur Cloud Shell
# et kubectl est déjà configuré pour parler à GKE
# ============================================================

[local]
localhost ansible_connection=local