name: CI/CD Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

env:
  PROJECT_ID: project-919f0101-d717-4509-b40
  REGISTRY: europe-west1-docker.pkg.dev
  IMAGE_NAME: bda-frontend

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generer le tag
        id: tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "Tag image : ${SHORT_SHA}"

      - name: Authentification GCP Workload Identity
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Configurer gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build et Push image frontend
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/bda-images/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.IMAGE_TAG }}"
          gcloud builds submit --tag "${IMAGE}" ./frontend/AdminBD_PostgreSQL_Frontend
          echo "Image poussee : ${IMAGE}"

      - name: Mettre a jour tag dans values.yaml
        run: |
          TAG="${{ steps.tag.outputs.IMAGE_TAG }}"
          sed -i "/bda-frontend/{n;s/tag: .*/tag: \"${TAG}\"/}" helm/bda/values.yaml
          echo "Verification apres modification :"
          grep -A 3 "bda-frontend" helm/bda/values.yaml

      - name: Commit et Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull origin main
          git add helm/bda/values.yaml
          git commit -m "ci: frontend tag ${{ steps.tag.outputs.IMAGE_TAG }} [skip ci]" || echo "Rien a committer"
          git push origin main
