namespace: bda

images:
  backend:
    repository: europe-west1-docker.pkg.dev/project-919f0101-d717-4509-b40/bda-images/bda-backend
    tag: "v1.0"
    pullPolicy: IfNotPresent
  frontend:
    repository: europe-west1-docker.pkg.dev/project-919f0101-d717-4509-b40/bda-images/bda-frontend
    tag: "df70c7a"
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent

database:
  name: versements
  user: versement_user
  passwordBase64: VmVyc2VtZW50U2VjcmV0MTIz
  port: 5432
  storageSize: 5Gi
  storageClass: standard-rwo

backend:
  replicaCount: 1
  port: 80
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 1
  port: 80
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

postgres:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  host: "bda.34.53.243.100.nip.io"
  className: nginx

hpa:
  backend:
    minReplicas: 1
    maxReplicas: 3
    cpuThreshold: 70
  frontend:
    minReplicas: 1
    maxReplicas: 3
    cpuThreshold: 70

pdb:
  backend:
    minAvailable: 1
  frontend:
    minAvailable: 1
